### ISSUE TITLE
Knowledge needed to successfully revive Lazarus

### ISSUE THREAD

**Issue by maphew** [lazarus-recovery/original_ff#4]
_The below continues a conversation started in another channel. For those just dropping in now, @xenomonkey was [instrumental in the original Lazarus](https://groups.google.com/a/chromium.org/d/msg/chromium-extensions/aoAIue0W47o/j3Bd86piPwAJ) extension. Due to historical promises made he will not contribute code, but he is happy to help with high level advice, reasons for what they did, and encouragement. That said with a lot of other stuff going on in his life his involvement will be reasonably passive._

> So even high level comments offering only advice are still of great benefit.

Advice can be easier in response to questions. 

What foundational knowledge, programming paradigms, and/or patterns do you consider essential or at least highly beneficial in re-building Lazarus? 
What problems would you assign a junior developer to tackle to get them prepared for being successful? 
What "attack order" would you suggest?

_Although I've opened this "issue" with questions directed specifically to xenomonkey, if you have something significant to add, as answer or question, please jump in. It's a conversation_

**Comment by hyiltiz** [comment]
I am not familiar with this project except being a regular user until FF-57 disabled it. Now, to port it to WebExtentions, I think we could strip down most additional features and keep the core feature first, then add in the rest over some time. Assuming this is a good direction to go, here are my questions that should be informative even if we don't go that way:

0. Can we have an exhaustive list of Lazarus' features so we can categorize them based on pure logical code, or browser API dependent code (see below)?

1. So, what are the core features that signifies Lazarus and separates it from other similar add-ons? 

2. How do these core features depend on XUL-based or other deprecated API? 

3. Which features (not only core features but among all features) are implemented as pure logical code, independent of browser APIs, such that they can be easily implemented into the WebExtention?

**Comment by sierracircle** [comment]
Closing this issue since we have successfully ported to WebExtension. Start a new thread for new issues.
